### ISSUE TITLE
Item Ban Message Spam on Tick

### ISSUE THREAD

**Issue by TheBambino** [saschahi/ItemControl#1]
Item banned message is spammed on every tick without `item.Name`.
![image](https://user-images.githubusercontent.com/9632779/129945771-4fa248d7-2338-45ae-ac7a-1f7e69a99c85.png)
![image](https://user-images.githubusercontent.com/9632779/129945862-da112497-31ad-4722-8757-1f51c12dae28.png)

**Comment by saschahi** [comment]
wait... none of my checks CAN even give you this message unless the top one is enabled. 

do you have an empty item in your list of banned items? that might possibly give you an item without a name

**Comment by saschahi** [comment]
cleared over discord. he had "empty items" in his banlist and my mod tried to ban the "nothing" in players inventories lmao
