### ISSUE TITLE
Right-Click Causes Auto-Swing & Breaks Grand Design

### ISSUE THREAD

**Issue by TheBambino** [saschahi/ItemControl#2]
Enable only Item Control, jump in game, then right-click with any weapon; especially Grand Design. Most items are spammed as if constantly right-clicking. Grand Design interface spams as well but the interface never appears as if it is being canceled rendering it unusable.
![Rclickbroke](https://user-images.githubusercontent.com/9632779/130366050-33cf3bc8-4828-4d50-87f3-79b711864af7.gif)

If I am not mistaken the culprit lies in the `AltFunctionUse` override.

**Comment by TheBambino** [comment]
PR #3 possible fix.

**Comment by saschahi** [comment]
I see the problem. working on it
